---
- name: Deploy webserver network on hosts
  hosts: webservers

  roles:

    - role: redhat.rhel_system_roles.network
      network_provider: nm
      network_connections:
        - name: eth1
          type: ethernet
          ip:
            address: 172.25.250.45/24

