---
- name: Deploy storage for webservers
  hosts: webservers

  roles:

    - role: redhat.rhel_system_roles.storage
      storage_pools:
        - name: vg_web
          type: lvm
          disks: /dev/vdb
          volumes:
            - name: lv_content
              size: 128m
              fs_type: xfs
              mount_point: /var/www/html/content
              state: present
            - name: lv_uploads
              size: 256m
              fs_type: xfs
              mount_point: /var/www/html/uploads
              state: present

