---
- name: Verify the sam user was created
  hosts: dev

  tasks:

    - name: Verify the same user exists
      ansible.builtin.user:
        name: sam
      check_mode: true
      register: sam_check

    - name: Print message about results
      when: sam_check['changed'] == false
      ansible.builtin.debug:
        msg: "Sam was created"

    - name: Output sam user status to file
      when: sam_check['changed'] == false
      ansible.builtin.lineinfile:
        path: /home/student/verify.txt
        line: "Sam was created"
        create: true

